[package]
name = "fast_download"
version = "0.1.0"
authors = ["Rui Loura <rui@joyent.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking"]}
failure = "0.1.8"
futures = "0.3.5"
tokio = {version = "0.2.21", features = ["fs", "io-util", "rt-core"]}
